[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
    directory = "functions/"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[build]
    edge_functions = "netlify/edge-functions"
    publish = ".next"